name: End-to-End Testing

on: 
 - workflow_dispatch
 - pull_request
 
jobs: 
  cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main
      
      - name: Install dependencies
        run: npm install
      
      - name: Run cypress tests with electron
        uses: cypress-io/github-actions@v5
        with:
         browser: electron