name: End to End Testing

on: 
 - workflow_dispatch
 - pull_request
 
jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout github actions
        uses: actions/checkout@master
        
      - name: Write the cypress file
        run: echo '${{ secrets.CYPRESS_ENV_FILE }}' > cypress.env.json
      
      - name: Run cypress tests
        run: cypress-io/github-action@v5
