name: End-to-End Testing

on: 
 - workflow_dispatch
 - pull_request
 
jobs: 
  cypress-run:
    runs-on: ubuntu-22.04
    steps: 
      - name: Checkout github actions
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install
        
      - name: Write the cypress file
        run: echo '${{ secrets.CYPRESS_ENV_FILE }}' > cypress.env.json
      
      - name: Cypress run
        run: cypress-io/github-actions@v5