name: End to End Testing

on: 
 - workflow_dispatch
 - pull_request
 
jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main
      
      - name: Install dependencies
        run: npm install
        
      - name: Write the cypress file
        run: echo '${{ secrets.CYPRESS_ENV_FILE }}' > cypress.env.json
      
      - name: Run cypress tests with electron
        uses: cypress-io/github-actions@v5
        with:
         browser: electron
         
