name: End-to-End Testing

on: 
 - workflow_dispatch
 - pull_request
 
jobs: 
  cypress-run:
    name: E2E testing
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v3
      
      - name: Cypress.io
        uses: cypress-io/github-action@v5
        with:
         browser: electron
