name: Unit testing

on:
- workflow_dispatch
- pull_request

jobs: 
  run-unit-test: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@master
    
    - name: Install dependencies
      run: npm install
    
    - name: Run unit tests
      run: npm run test-unit
